import GlobalNav from './GlobalNav';
import './globals.css';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <head>
        <title>New routing next13</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </head>
      <body>
        <GlobalNav />
        <main>{children}</main>
      </body>
    </html>
  );
}
